<template>
  <component :is="icon" v-bind="$attrs" :width="size" :height="size" />
</template>

<script>
import {
  Activity,
  Alert,
  AlignCenter,
  AlignJustify,
  AlignRight,
  ArrowLeft,
  ArrowLeftNarrow,
  ArrowRight,
  ArrowRightNarrow,
  ArrowUp,
  ArrowUpNarrow,
  Attachment01,
  Attachment02,
  Backpack,
  BarChart01,
  Bell,
  BellRing,
  Bold,
  Book,
  Box,
  Building01,
  Calendar,
  Calendar01,
  Camera01,
  Car01,
  Check,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ChevronDownDouble,
  ChevronUpDouble,
  ChevronLeftDouble,
  ChevronRightDouble,
  Clock,
  Close,
  CloseCircle,
  CloseSquare,
  Code02,
  Compass03,
  Copy01,
  Document,
  DollarSymbol,
  Download01,
  Download02,
  Envelope,
} from './index.js'

export default {
  name: 'MyVueIcons',
  components: {
    Activity,
    Alert,
    AlignCenter,
    AlignJustify,
    AlignRight,
    Attachment01,
    Attachment02,
    ArrowLeft,
    ArrowLeftNarrow,
    ArrowRight,
    ArrowRightNarrow,
    ArrowUp,
    ArrowUpNarrow,
    Attachment01,
    Attachment02,
    Backpack,
    BarChart01,
    Bell,
    BellRing,
    Bold,
    Book,
    Box,
    Building01,
    Calendar,
    Calendar01,
    Car01,
    Camera01,
    Check,
    ChevronDown,
    ChevronUp,
    ChevronLeft,
    ChevronRight,
    ChevronDownDouble,
    ChevronUpDouble,
    ChevronLeftDouble,
    ChevronRightDouble,
    Clock,
    Close,
    CloseCircle,
    CloseSquare,
    Code02,
    Compass03,
    Copy01,
    Document,
    DollarSymbol,
    Download01,
    Download02,
    Envelope,
    Settings01,
    Settings02,
  },
  props: {
    icon: {
      type: String,
      required: true,
      validator: (value) => {
        return [
          'Activity',
          'Alert',
          'AlignCenter',
          'AlignJustify',
          'AlignRight',
          'Attachment01',
          'Attachment02',
          'ArrowLeft',
          'ArrowLeftNarrow',
          'ArrowRight',
          'ArrowRightNarrow',
          'ArrowUp',
          'ArrowUpNarrow',
          'Car01',
          'Camera01',
          'Attachment01',
          'Attachment02',
          'Backpack',
          'BarChart01',
          'Bell',
          'Calendar',
          'Calendar01',
          'Camera01',
          'Check',
          'ChevronDown',
          'ChevronUp',
          'ChevronLeft',
          'ChevronRight',
          'ChevronDownDouble',
          'ChevronUpDouble',
          'ChevronLeftDouble',
          'ChevronRightDouble',
          'Clock',
          'Close',
          'CloseCircle',
          'CloseSquare',
          'Code02',
          'Compass03',
          'Copy01',
          'Document',
          'DollarSymbol',
          'Download01',
          'Download02',
          'Envelope',
          'Settings01',
          'Settings02',
        ].includes(value) // Add more icons here
      },
    },
    size: {
      type: [String, Number],
      default: 24,
    },
  },
}
</script>
